### ISSUE TITLE
大佬这个algolia搜索功能是每上传一个blog文件就要运行一次抓取的嘛

### ISSUE THREAD

**Issue by onewhitethreee** [kuizuo/blog#161]
好麻烦哦，有没有啥解决方法啊🥲

**Comment by kuizuo** [comment]
我目前algolia搜索功能是Docsearch每周定时爬一次，但是也可以手动到管理面板让Docsearch爬取一次，但是需要申请会比较麻烦。

![image](https://user-images.githubusercontent.com/61005888/183274371-ae3599c8-6c53-4b8d-8680-4d3ae6fefac7.png)

如果不申请的话就只能自己创建爬虫配置文件与环境，然后开始爬取。我当时就是封装了npm scripts然后每次部署的时候在执行一遍命令

```
"scripts": {
  "index": "docker run -it --env-file=.env -e \"CONFIG=$(cat docsearch.json | jq -r tostring)\" algolia/docsearch-scraper"
},
```

**Comment by onewhitethreee** [comment]
好⑧，谢谢
