### ISSUE TITLE
网站插画

### ISSUE THREAD

**Issue by Ryanjiena** [kuizuo/blog#191]
想问一下，网站首页这种风格的插画是在哪里下载的呢( ´･･)ﾉ(._.`) 谢谢

**Comment by kuizuo** [comment]
https://undraw.co/

在上面这个网站中能找到许多免费类似的风格的插画图，其实我在 [主题魔改](https://kuizuo.cn/docs/docusaurus-style#%E4%B8%BB%E9%A1%B5) 中有介绍到插画图来源，如果你有想修改的部分也可到这里看看。
