### ISSUE TITLE
kuizuo大佬你好，我想向你请教你一个Navbar的问题

### ISSUE THREAD

**Issue by BlueOrgreen** [kuizuo/blog#198]
这是我模仿你的blog的，上面的Navbar不显示
![image](https://user-images.githubusercontent.com/64401491/225583100-44dfe9c5-48c5-4535-a76a-791385ad775f.png)

这是大佬你的
![image](https://user-images.githubusercontent.com/64401491/225583351-df4b261f-c81d-4030-858d-d4c7633fcc20.png)

实在抱歉，在百忙之中耽误大佬时间了

**Comment by kuizuo** [comment]
能否提供你当前项目的配置文件 `docusaurus.config.js` 或者你的仓库地址以提供最小复现，我好帮你分析问题。

**Comment by BlueOrgreen** [comment]
kuizuo大佬，这是我的仓库地址
https://github.com/BlueOrgreen/Fanyun-Website


默言忆旧
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kuizuo/blog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月16日(星期四) 晚上6:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kuizuo/blog] kuizuo大佬你好，我想向你请教你一个Navbar的问题 (Issue #198)





 
能否提供你当前项目的配置文件 docusaurus.config.js 或者你的仓库地址以提供最小复现，我好帮你分析问题。

**Comment by kuizuo** [comment]
已私聊解决.
