### ISSUE TITLE
好像不支持公式🤔

### ISSUE THREAD

**Issue by qzlu-cyber** [kuizuo/blog#220]
很棒的模板，但是公式渲染不出来，我按照官网的方法加了两个package但好像还是不行😢……
![image](https://github.com/kuizuo/blog/assets/53920473/41cb0d39-37f9-46a3-95fe-4995b32b6f0d)
![image](https://github.com/kuizuo/blog/assets/53920473/ad6c056e-cb52-43ef-be1a-6f88ed9e4490)

**Comment by kuizuo** [comment]
在这个分支中 https://github.com/kuizuo/blog/tree/katex 有配置好数学公式，不过当时的主题版本与现在有所差异，你可以对比 commit https://github.com/kuizuo/blog/commit/4e9b3f6ce4dfe860b9db1d1fc1e55863550e6278 来查看相关配置。

你配置没生效的话，有可能是你只配置的 docs 下的文档，而你在 blog 下使用到了数学公式，那肯定是不会生效。

如果可以的话提供更详细的信息以帮助你解决。😉

**Comment by qzlu-cyber** [comment]
> 在这个分支中 https://github.com/kuizuo/blog/tree/katex 有配置好数学公式，不过当时的主题版本与现在有所差异，你可以对比 commit [4e9b3f6](https://github.com/kuizuo/blog/commit/4e9b3f6ce4dfe860b9db1d1fc1e55863550e6278) 来查看相关配置。
> 
> 你配置没生效的话，有可能是你只配置的 docs 下的文档，而你在 blog 下使用到了数学公式，那肯定是不会生效。
> 
> 如果可以的话提供更详细的信息以帮助你解决。😉

好的，我先试试😊我在 docs 下也试了，同样是无法生效😐

**Comment by qzlu-cyber** [comment]
官网给的配置和你分支中的一样哎，但还是不生效😢

**Comment by kuizuo** [comment]
> 官网给的配置和你分支中的一样哎，但还是不生效😢

能否提供最小复现（仓库）? 这边帮你看看

**Comment by qzlu-cyber** [comment]
> > 官网给的配置和你分支中的一样哎，但还是不生效😢
> 
> 能否提供最小复现（仓库）? 这边帮你看看

https://github.com/qzlu-cyber/blog 感谢

**Comment by kuizuo** [comment]
由于使用了docusaurus@v3，因此需要参考最新文档 https://docusaurus.io/zh-CN/docs/3.0.0-alpha.0/markdown-features/math-equations#configuration

你所要做的步骤如下：

执行 `pnpm add remark-math@5 rehype-katex@6` 以获取最新依赖

然后将 docusaurus.config.js 的配置改成下方形式

```typescript
module.exports = async function createConfigAsync() {
  return {
    title: 'Docusaurus',
    tagline: 'Build optimized websites quickly, focus on your content',
    presets: [
      [
        '@docusaurus/preset-classic',
        {
          docs: {
            path: 'docs',
            remarkPlugins: [(await import('remark-math')).default],
            rehypePlugins: [(await import('rehype-katex')).default],
          },
        },
      ],
    ],
    stylesheets: [
      {
        href: 'https://cdn.jsdelivr.net/npm/katex@0.13.24/dist/katex.min.css',
        type: 'text/css',
        integrity:
          'sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM',
        crossorigin: 'anonymous',
      },
    ],
  };
};
```

此时就能生效了 
![image](https://github.com/kuizuo/blog/assets/61005888/bb86e1b0-0628-42c1-a8e7-6d9ebd6aef6e)

**Comment by qzlu-cyber** [comment]
成功了，非常感谢。不过看来最开始我做的是对的，但是只设置了 docs，没设置 blog，然后又找了老版的配置🤣docs 和 blog 都不生效了😂非常非常感谢你的模板和帮助👍
![image](https://github.com/kuizuo/blog/assets/53920473/d3c56d61-d481-431f-82d1-482b7f26ea33)
