### ISSUE TITLE
可以加个运行时间的吗

### ISSUE THREAD

**Issue by ahKevinXy** [kuizuo/blog#222]
在底部 加个网站运行时长的小部件吗

**Comment by kuizuo** [comment]
加一个这个小部件并不是很难，定义好网站上线的时间，输出当前时间与上线时间的差便可，至于样式随你喜欢的来设计即可。

我个人是不太想添加这样的部件

**Comment by ahKevinXy** [comment]
我加好了好像，但是写的很lower
