### ISSUE TITLE
移动端侧边栏切换语言问题

### ISSUE THREAD

**Issue by 0xMacintosh** [kuizuo/blog#241]
您好，我尝试克隆您的repo并客制化成自己的个人网站，但是我遇到了一个问题不知道怎么解决。

这是我的repo链接：https://github.com/0xMacintosh/personal-website.git
这是我的部署网站：https://0xmacintosh.ca/

在desktop状态下，切换语言正常工作，但在mobile状态下的侧边导航栏中，出现了一些问题。我的默认语言是en，当我切换成zh-Hant之后，侧边导航栏的切换语言链接会有问题。
<img width="618" alt="image" src="https://github.com/kuizuo/blog/assets/152773252/489a23f8-d134-4ae9-a130-be516735e154">

<img width="616" alt="image" src="https://github.com/kuizuo/blog/assets/152773252/8e7c74ca-991f-46f1-a49d-00d917aa58ac">

不知道是否能麻烦您看一看，因为我找了所有的官方文档还是不知道怎样解决。万分感激！！

**Comment by kuizuo** [comment]
我查看了一下你的仓库，在 i18n 目录下  https://github.com/0xMacintosh/personal-website/tree/main/i18n/zh 你只定义了 zh 目录，而没有 zh-hant。

**Comment by kuizuo** [comment]
你这个问题有点棘手，确实存在移动端情况下，跳转到 https://zh-hant。不知道你是否有尝试过其他语言，是否有类似的情况，还是说只有繁体中文有这种情况？

**Comment by 0xMacintosh** [comment]
> 你这个问题有点棘手，确实存在移动端情况下，跳转到 https://zh-hant 不知道你是否有尝试过其他语言，是否有类似的情况，还是说只有繁体中文有这种情况？

我确实还没有试过其他语言，我试一下再回复您。感谢！

**Comment by 0xMacintosh** [comment]
我又试了几种语言，还是有一样的问题，不知道是不是因为我用Netlify部署导致的。现在我删除了i18n的配置，也算解决问题了。感谢作者大大的回复！

**Comment by kuizuo** [comment]
> 我又试了几种语言，还是有一样的问题，不知道是不是因为我用Netlify部署导致的。现在我删除了i18n的配置，也算解决问题了。感谢作者大大的回复！

应该是 Netlify 部署导致的，我在本地构建你的项目运行并未出现该异常。

不过令我好奇的是为啥在移动端或页面宽度为移动端的情况下会导致出现该 bug 😂

**Comment by 0xMacintosh** [comment]
> > 我又试了几种语言，还是有一样的问题，不知道是不是因为我用Netlify部署导致的。现在我删除了i18n的配置，也算解决问题了。感谢作者大大的回复！
> 
> 应该是 Netlify 部署导致的，我在本地构建你的项目运行并未出现该异常。
> 
> 不过令我好奇的是为啥在移动端或页面宽度为移动端的情况下会导致出现该 bug 😂

是的，我在本地也是没有发现问题。是啊，按理来说桌面端和移动端用的应该是同一个组件才对，如果有问题应该同时有才对😂
