### ISSUE TITLE
/archive 页面 404，应该指向 /blog/archive

### ISSUE THREAD

**Issue by yandif** [kuizuo/blog#259]
## 界面位置
<img width="400" alt="image" src="https://github.com/kuizuo/blog/assets/52165593/64ca43bf-a980-465a-a1e9-7db66d390114">

## 文件位置
路径：blog/src/components/UserCard/index.tsx

<img width="886" alt="image" src="https://github.com/kuizuo/blog/assets/52165593/5cabec92-6446-4ebe-aaf5-7f5ea25d2391">

**Comment by kuizuo** [comment]
感谢反馈
