### ISSUE TITLE
📊 Catalogue 目录树

### ISSUE THREAD

**Issue by itchaox** [kuizuo/blog#269]
你好，请问下你的 📊 Catalogue 目录树是如何生成的，以及如何编写对应的注释，谢谢

**Comment by kuizuo** [comment]
macos 可以通过安装 [tree](https://formulae.brew.sh/formula/tree)，或者使用 node 安装 treer 来实现，我一般使用前者。

通过进入到指定目录后，执行以下命令便可生成对应目录树结构，根据需要进行删改便可。

```
tree -L 2 -I 'node_modules'
```

至于后面对应的注释，就要靠开发者自行编写了。

**Comment by itchaox** [comment]
> macos 可以通过安装 [tree](https://formulae.brew.sh/formula/tree)，或者使用 node 安装 treer 来实现，我一般使用前者。
> 
> 通过进入到指定目录后，执行以下命令便可生成对应目录树结构，根据需要进行删改便可。
> 
> ```
> tree -L 2 -I 'node_modules'
> ```
> 
> 至于后面对应的注释，就要靠开发者自行编写了。

了解了，谢谢
