### ISSUE TITLE
Error Adapt 

### ISSUE THREAD

**Issue by fernandogprieto** [kuizuo/blog#303]
Hey bro I tried to adapt the website to my needs. I'm not a Developer, I'm Cloud Engineer.. so I feel I lost a lot of time trying to adapt your website Do u have other method to adapt the website.
- Gicus (not)
- Baitu (not)
- Beian something about the Chinese Government to publish (Not).
- Spanish and English (Currently, I have an error to build locale)

I like your design, do u have a design form scratch or simple methods to adapt your website, please?

**Comment by kuizuo** [comment]
Thank you for liking my theme design. You may need a lightweight version.
In fact, I have tried to write a theme for Docusaurus before. But this will lead to many functions that cannot be customized, such as comments(with giscus), so I give up.

The functions you don't need are actually very easy to delete, just like the plugin, you can remove it after you find it, 
copy the page and functions you need.
