### ISSUE TITLE
new idea

### ISSUE THREAD

**Issue by fernandogprieto** [kuizuo/blog#304]
![image](https://github.com/kuizuo/blog/assets/113651560/bb547bd3-6681-42cc-a0e8-5ae093439bdf)

Bro could you add another option similar to this to create suggestions or something like that?

**Comment by kuizuo** [comment]
This project is just my personal blog, so I'm too lazy to create a issue template.😂

**Comment by fernandogprieto** [comment]
lol only create a suggest section and  bug report! please! @kuizuo you delete the feature abut github landinpage ?
![image](https://github.com/kuizuo/blog/assets/113651560/e63a8242-f990-444a-90f0-c81b53cc0980)

you don't want any more the landingpage?

**Comment by kuizuo** [comment]
> lol only create a suggest section and bug report! please! @kuizuo you delete the feature abut github landinpage ? ![image](https://private-user-images.githubusercontent.com/113651560/345923401-e63a8242-f990-444a-90f0-c81b53cc0980.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNjE3OTgsIm5iZiI6MTcyMDI2MTQ5OCwicGF0aCI6Ii8xMTM2NTE1NjAvMzQ1OTIzNDAxLWU2M2E4MjQyLWY5OTAtNDQ0YS05MGYwLWM4MWI1M2NjMDk4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxMDI0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjg2Y2FlMjZkOGRhYmQ0NTE1NmExNmYzMmNlZjYyMWM5OTYyMzdiMjZmY2RhMjQyOWVhZGQ3ZTdiN2M2Mzk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ce6DPwfiDYLDVW13mfIG5wC1tQc7XN9cPCu4SdfsLBQ)
> 
> you don't want any more the landingpage?

I hidden it other than delete it, because I will redesign it and move to about page.
