### ISSUE TITLE
Need to help about npm start failed 

### ISSUE THREAD

**Issue by heywalter** [kuizuo/blog#315]
When I run pnpm start, the logs are printed below. Any suggestions? Thank you.

[INFO] Starting the development server...
(node:2870) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.

[ERROR] TypeError: Cannot read properties of undefined (reading 'replace')
    at formatPluginName (/Users/walter/Documents/GitHub/blog/node_modules/.pnpm/@docusaurus+core@3.4.0_@docusaurus+types@3.4.0_react-dom@18.3.1_react@18.3.1_typescript@5.5.4/node_modules/@docusaurus/core/lib/server/plugins/pluginsUtils.js:70:35)
....

**Comment by kuizuo** [comment]
Can you clone the latest main branch? 

if the problem still exists, please provide a minimal reproduction and I will help you fix it.

**Comment by heywalter** [comment]
> Can you clone the latest main branch?
> 
> if the problem still exists, please provide a minimal reproduction and I will help you fix it.

Hi, thanks for your help, I tried to clone the latest main, and the issue was solved, though there are some warning logs likes below:
```
> blog@3.0.0 start
> docusaurus start

[INFO] Starting the development server...
(node:93113) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:93113) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
[SUCCESS] Docusaurus website is running at: http://localhost:3000/

✔ Client
  Compiled successfully in 1.76s

client (webpack 5.94.0) compiled successfully
```

**Comment by kuizuo** [comment]
Don't worry, it's just a warning. Just ignore them.
